### ISSUE TITLE
Help for audio

### ISSUE THREAD

**Issue by wes1993** [andrey-kondratov/juancamera-proxy#3]
Hello, 
thanks a lot for your server, 
there is a way to also capture the audio?

some useful info:
```
£©: (ø'´E&,@çÀ¨4À¨}íPº_<ë³ÝP¡GET /netsdk/audio/encode/channel/101 HTTP/1.1
Accept: application/json, text/javascript, */*
Authorization: Basic YWRtaW46
Content-Type: application/x-www-form-urlencoded
Connection: keep-alive
Host: 192.168.0.136
User-Agent: channel properties

(ø'´£©: Eq5M@@-À¨À¨4P}íë³Þº`:PÕÖ{"id":101,"enabled":true,"audioInputChannelID":1,"codecType":"G.711alaw"}

```
```
(ø'´£©: Eq5M@@-À¨À¨4P}íë³Þº`:PÕÖ{"id":101,"enabled":true,"audioInputChannelID":1,"codecType":"G.711alaw"}
(ø'´£©: Eºö5@@ÁûÀ¨À¨4P}ìîAUWIPãESession: 42
Cseq: 1
m=video 97 H265/90000/2304/1296
m=audio 8 G711/8000/2
Transport: RTP/AVP/TCP;unicast;hisiinterleaved=0-1;ssrc=0000002a
```
Again thanks
Stefano

**Comment by andrey-kondratov** [comment]
It actually returns audio but you have to demux it from the stream. See my .NET Core implementation of this

https://github.com/andead/juancamera-proxy-netcore/blob/master/JuanIpCamera.ConsoleApp/Program.cs#L21-L22

Which is based on the same Gist https://gist.github.com/maxious/c8915a436b532ab09e61bf937295a5d2#file-stream-socket-py

Since my proxy app works with a single socket, and I am not an expert in audio/video streaming, I just left it as is. I would assume some multiplexing into a standard format would be required so that the proxy would act as a media stream server compatible with HTML5 etc. I also believe I tried to do it using `ffplay` configuration + what is now implemented in the app, but in the end I don't remember if that worked. 🤷🏻‍♂️

**Comment by wes1993** [comment]
Thanks a lot for your reply!! I have found some other information on this, also substream mainstream etc, I have also found a way to change the audio from G711 to AAC, do you have telegram? I really want to create some wonderful proxy for this Chinese cam ;)

**Comment by wes1993** [comment]
P.S. do you think that using AAC also need decode?

**Comment by andead** [comment]
Let's talk at https://t.me/joinchat/U0wy8Rm7zPU0N2Qy

**Comment by andrey-kondratov** [comment]
I've stopped using this camera and will archive the project.
